// Package fixtures describes the layout of a generated test world and
// provides path helpers so tests don't hardcode strings.
//
// The actual world is generated by running `go run ./test/fixtures/gen`
// (or `make fixtures`). Tests then read from the generated directories.
package fixtures

import "path/filepath"

// World holds the root paths of a generated fixture environment.
type World struct {
	Root      string // base directory, e.g. /tmp/grove-fixtures
	CodeRoot  string // Root/code  — set as GROVE_CODE_ROOT
	VaultRoot string // Root/vault — set as GROVE_HOME_ROOT
}

// New returns a World whose paths are rooted at dir.
func New(dir string) *World {
	return &World{
		Root:      dir,
		CodeRoot:  filepath.Join(dir, "code"),
		VaultRoot: filepath.Join(dir, "vault"),
	}
}

// CodeContainer returns the container directory for a project inside CodeRoot.
// Example: w.CodeContainer("kalashnikov") → <root>/code/kalashnikov
func (w *World) CodeContainer(project string) string {
	return filepath.Join(w.CodeRoot, project)
}

// VaultPath returns a path inside VaultRoot.
// Example: w.VaultPath("01-Projects", "grove") → <root>/vault/01-Projects/grove
func (w *World) VaultPath(parts ...string) string {
	return filepath.Join(append([]string{w.VaultRoot}, parts...)...)
}

// DefaultRoot is the path used by `make fixtures` and the Dockerfile.
const DefaultRoot = "/tmp/grove-fixtures"
